project:
  type: manuscript
  render:
    - main.qmd
    - supplementary_materials.qmd
manuscript:
  article: main.qmd
  code-links: repo
  #notebooks:
   # - supplementary_materials.qmd

format:
  html: default
  docx:
    notebook-links: false
  science-pdf:
    journal: "scicite"
    keep-tex: true
    toc: false
    notebook-links: false
    include-in-header:
      text: '\usepackage{lineno}\linenumbers'
  #nature-pdf:
  #  journal:
  #    cite-style: sn-nature
  #  cite-method: natbib
  #  toc: false
  #  notebook-links: false
   # lineno: true
  #  equalmargins: true


#environmnet: "renv.lock"
execute:
  freeze: false
