---
title: "Code for Supplementary Figures and Tables: Projected warming will exceed the long-term thermal limits of rice cultivation"
format: pdf
editor: visual
html-table-processing: none
---

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(dev = 'png', echo = FALSE, results = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(sf)
library(stars)
library(ggridges)
library(patchwork)
library(units)
library(rnaturalearth)
library(rnaturalearthdata)
library(here)
library(eks)

theme_set(theme_bw())

# define the study area
asia_bbox_sf <- st_bbox(c(xmin = 60, xmax = 150, ymin = -11, ymax = 54), crs = 4326)
world_bbox_sf <- st_bbox(c(xmin = -130, xmax = 155, ymin = -40, ymax = 60), crs = 4326)

# get country boundaries shapefile for plotting
sf_use_s2(FALSE)
countries <- ne_countries(scale = 'large') %>% 
  st_crop(asia_bbox_sf)
countries_small<- ne_countries() %>%
  st_crop(asia_bbox_sf)
coasts <- ne_coastline() %>%
  st_crop(asia_bbox_sf)
coasts_world <- ne_coastline() %>% 
  st_crop(world_bbox_sf)
countries_world <- ne_countries(scale = 'large') %>% 
  st_crop(world_bbox_sf)
sf_use_s2(TRUE)

country_stats <- readRDS('data/data-derived/country_stats.rds') # country level stats

load(here('data/data-derived/occurrence_data.RData'))

arch_trace_dat <- readRDS(here('data/data-derived/arch_trace.rds')) |>
  mutate(mil = (med_age - med_age %% 1000) / 1000 + 1) |>
  filter(between(mil, -9, -2)) |> # reduces to 542 unique sites
  mutate(mil = as.factor(mil)) 

fig2_dat <- irri_occ %>%
  st_drop_geometry() %>%
  select(bio1, bio5, bio10) %>%
  mutate(across(everything(), ~units::set_units(.x, 'degree_C')))

quantiles <- c(0.01, 0.025, 0.05, 0.1, 0.9, 0.95, 0.975, 0.99)

quants_mod <- fig2_dat %>%
  reframe(across(everything(), 
                   ~quantile(.x, quantiles, type = 8))) %>%
  round(1) %>%
  mutate(quantile = quantiles, .before = 1)

quant_975 <- filter(quants_mod, quantile == 0.975)
bio1_limit <- quant_975$bio1
bio5_limit <- quant_975$bio5
bio10_limit <- quant_975$bio10

model_names <- c('gfdl', 'ipsl', 'mpi', 'mri', 'ukesm')
ssp_names <- c('ssp126', 'ssp370', 'ssp585')

cmip6 <-  model_names %>%
  map(paste,  ssp_names, sep = '/' ) %>%
  map_depth(1, ~paste0('~/Dropbox (UFL)/Data/CHELSA/CMIP6/2071-2100/', .x, '/bio') %>% as.list()) %>%
  map_depth(2, ~list.files(.x, full.names = TRUE, pattern = '*_bio1_|_bio5_|_bio10_*')) %>%
  map_depth(2, ~read_stars(.x) %>%
              setNames(c('bio1', 'bio10', 'bio5')) %>%
              st_redimension()) %>%
  map(~do.call('c', .x) %>% 
        setNames(c('SSP1-2.6', 'SSP3-7.0', 'SSP5-8.5')) %>% 
        st_redimension()) %>%
  do.call('c', .) %>%
  setNames(model_names) %>%
  st_redimension() %>%
  st_set_dimensions(names = c('x', 'y', 'variable', 'ssp', 'model')) %>%
  setNames('temperature') %>%
  .[countries]
```

## Fig. S1.

```{r}
#| label: fig-bootstrap
#| fig-width: 6
#| fig-height: 4
#| fig-cap: "A) Bootstrapped kernel density estimates of rice's thermal extent throughout the Holocene. Bootstrap resampling accounts for uncertainty in radiocarbon and phase-based dating of archaeological rice finds. Contemporary temperature tresholds indicated in red. B) Estimated 97.5% quantiles from the bootstrapped dataset. Contemporary quantiles indicated in red."

trace_boot <- readRDS('data/data-derived/trace_boot.rds')

# contemporary quantiles for plotting
quant_dat <- quant_975 |>
               select(-quantile) |>
               setNames(c('MAT', 'tmax', 'twarm')) |>
              pivot_longer(everything())

boot_1 <- trace_boot %>%
  filter(time <= -2000) %>%
  select(rep, MAT:twarm) %>%
  pivot_longer(MAT:twarm) %>%
  group_by(rep, name) %>%
  tidy_kde() %>%
ggplot(aes(value, estimate)) +
  geom_line(alpha = 0.01, aes(group = rep)) +
  facet_wrap(~name, scales = 'free_y', nrow = 3) +
  geom_vline(data = quant_dat, aes(xintercept = as.numeric(value)), linetype = 2, color = 'red') +
  labs(x = 'Temperature')

boot_2 <- trace_boot %>%
  filter(time <= -2000) %>%
  pivot_longer(MAT:twarm, values_to = 'temperature') %>%
  mutate(temperature = units::set_units(temperature, 'degree_c')) %>%
  group_by(rep, name) %>%
  reframe(value = quantile(temperature, 0.975, type = 8)) %>%
  ggplot(aes(value)) +
    geom_histogram() +
    facet_wrap(~name, scales = 'free_x', nrow = 3) +
    labs(x = 'Temperature') +
    theme_bw() +
    geom_vline(data = quant_dat, aes(xintercept = value), linetype = 2, color = 'red')

rm(trace_boot, quant_dat)

boot_1 + boot_2 +  plot_annotation(tag_levels = 'A')
```

{{< pagebreak >}}

## Fig. S2.

```{r}
#| label: fig-recon-timeseries
#| fig-width: 12
#| fig-height: 6
#| fig-cap: "Comparison of Holocene temperature trends over Asia from transient climate models and reconstructions. A) Holocene trends in mean annual temperature, relative to the 3-5ka mean, from Osman et al. 2021 (black, one standard deviation uncertainty in grey), Erb et al. 2022 (blue), and CHELSA-TraCE21k (red). B) Comparison of annual, seasonal, and monthly temperature trends over Asia from CHELSA-TraCE21k."

#erb_decadal <- readRDS('data/data-derived/older_file_archive/erb_decadal.rds')

# trace_order <- list.files('~/Dropbox (UFL)/Data/CHELSA/chelsa_trace/bio01', 
#                           full.names = FALSE) %>%
#   str_sub(23, -10) %>% 
#   as.numeric() %>% 
#   order()
# 
# sf_use_s2(FALSE)
# chelsa_trace <- list('bio01', 'bio05', 'bio10') |>
#   map(~ paste0('~/Dropbox (UFL)/Data/CHELSA/chelsa_trace/', .x) |>
#         list.files(full.names = TRUE) %>%
#         .[trace_order] |>
#         read_stars(along = 'time') |>
#           st_downsample(n = 50) |>
#   st_crop(st_bbox(erb_decadal))) %>%
#   do.call('c', .) |>
#   st_set_dimensions('time', values = seq(12, 0, -0.1), names = 'time') |>
#   setNames(c('bio1', 'bio5', 'bio10'))

# lgmr_ens <- read_ncdf('~/Dropbox (UFL)/LGMR_SAT_climo.nc', eps = .001, proxy = FALSE) |>
#   st_crop(st_bbox(erb_decadal)) |>
#   units::drop_units() |>
#   st_set_dimensions(names = c('x', 'y', 'time')) |>
#   filter(time <= 12000) |>
#   mutate(sat_low = sat - sat_std,
#          sat_high = sat + sat_std) |>
#   st_apply(3, mean) |>
#   as_tibble() |>
#   mutate(time = time / 1000) 

#sf_use_s2(TRUE)


trace_ts <- read_rds(here('data/data-derived/trace_ts.rds'))

a <- trace_ts |>
  pivot_longer(-time) |>
  mutate(name = factor(case_when(name == 'bio1' ~ 'Mean annual temperature',
                                 name == 'bio5' ~  'Max temperature of warmest month',
                                 name == 'bio10' ~  'Max temperature of the warmest quarter'),
                        levels = c('Mean annual temperature', 
                                   'Max temperature of the warmest quarter',
                                   'Max temperature of warmest month'))) |>
  ggplot() +
  geom_line(aes(time, value, group = name)) +
  facet_wrap(~name, scales = 'free_y', ncol = 1) +
  labs(x = 'Time (ka BP)', y = 'Temperature (C)') +
  scale_x_reverse(breaks = seq(0, 12, 2)) +
  theme_bw()

# run separately to get the 3-5ka mean to subtract in the following plot
#lgmr_ens |>
#  filter(between(time, 3, 5)) |>
#  summarize(across(everything(), mean))

#trace_ts |>
#  filter(between(time, 3, 5)) |>
#  summarize(across(everything(), mean))

# Calculate the area-weighted averaged temperatures and uncertainties from the Erb et al. reconstruction and save the results.
erb_rast <- read_rds(here('data/data-derived/erb_rast.rds'))

erb_area_total <- st_area(erb_rast) |>
  pull(area) |> 
  sum()

erb_ts <- (erb_rast * st_area(erb_rast)) |>
  st_apply(3, sum)  |>
  as_tibble() |>
  mutate(across(-ages, ~units::drop_units(.x / erb_area_total)),
         time = ages / 1000) |>
  select(-ages)

# Do the same for the LGMR, although this is more complicated as we have to calculate the anomalies by hand for comparison to Erb.

lgmr_rast <- read_rds('data/data-derived/lgmr_rast.rds')

lgmr_mean_reference <- lgmr_rast |>
  filter(between(time, 3000, 5000)) |>
  st_apply(1:2, mean)

lgmr_sd_reference <- lgmr_rast |>
  filter(between(time, 3000, 5000)) |> 
  select(sat_std) |>
  # we need to account for uncertainty in the reference period too
  st_apply(1:2, function(x) sqrt(sum(x^2) / 11) / sqrt(11)) # 11 is the number of time steps

lgmr_uncertainty <- sqrt(lgmr_rast['sat_std'] ^ 2 + lgmr_sd_reference ^ 2)

lgmr_rast_anom <- lgmr_rast['sat'] - lgmr_mean_reference['sat']

lgmr_anomalies <- c(anom = lgmr_rast_anom,
  anom_upper = lgmr_rast_anom + lgmr_uncertainty,
  anom_lower = lgmr_rast_anom - lgmr_uncertainty)

lgmr_area_total <- st_area(lgmr_rast_anom) |>
  as_tibble() |>
  pull(area) |>
  sum()

lgmr_anom_ts <- (lgmr_anomalies * st_area(lgmr_rast_anom)) |>
  st_apply(3, sum)  |>
  as_tibble() |>
    mutate(across(-time, ~units::drop_units(.x / lgmr_area_total)),
           time = time / 1000)

#erb_ts2 <- erb_decadal |>
#  st_apply(3, mean) |>
#  as_tibble() |>
#  mutate(time = time / -1000)


 b <- #lgmr_ens |>
  ggplot(data = lgmr_anom_ts, aes(x = time)) +
  # geom_line(aes(x = time, y = sat - 20.23)) +
  # geom_ribbon(aes(x = time, ymin = sat_low - 20.23, ymax = sat_high - 20.23), alpha = 0.1) +
  geom_line(aes(y = anom)) +
  geom_ribbon(aes(ymin = anom_lower, ymax = anom_upper), alpha = 0.1) +
  geom_line(data = trace_ts, aes(x = time, y = bio1 - 19.737), color = 'red') +
    geom_line(data = erb_ts, aes(y = sat_mean), color = 'blue') +
    geom_ribbon(data = erb_ts, aes(ymin = sat_low , ymax = sat_high), alpha = 0.1, fill = 'blue') +
  scale_x_reverse(breaks = seq(0, 12, 2))  +
  labs(x = 'Time (ka BP)', y = 'Temperature anomaly (C)') 

#  lgmr_ens |>
#   ggplot(aes(time)) +
#   geom_line(aes(y = sat )) +
#   geom_ribbon(aes(ymin = sat_low , ymax = sat_high ), alpha = 0.1) +
#   geom_line(data = trace_ts, aes(y = bio1 ), color = 'red') +
#   scale_x_reverse(breaks = seq(0, 12, 2))  +
#   labs(x = 'Time (ka)', y = 'Temperature (C)') 

b + a + plot_layout(guides = 'collect', axes = 'collect') + plot_annotation(tag_levels = 'A', tag_suffix = ')')
```
{{< pagebreak >}}

## Fig. S3.

```{r}
#| label: fig-kde-lgmr
#| fig-width: 10
#| fig-height: 6
#| fig-cap: ""

new_lgmr_times <- lgmr_rast |>
  st_get_dimension_values('time') |>
  years() %>%
  `-`(ym('1950-01'), .)

lgmr2 <- lgmr_rast |>
  st_set_dimensions('time', values = (new_lgmr_times)) %>%
  .[,,,61:1]

lgmr_extract_test <- arch_trace_dat |>
  mutate(time = ym('1950-01') - years(as.integer(med_age) * -1)) %>%
  st_extract(lgmr2, ., time_column = 'time', interpolate_time = TRUE) %>%
  st_drop_geometry() %>%
  bind_cols(arch_trace_dat, .) |>
  remove_missing()

arch_dens_mat <- arch_trace_dat %>%
  ggplot(aes(MAT, mil)) +
  scale_y_discrete(limits = rev) +
  geom_density_ridges(aes(fill = mil), 
                      panel_scaling = TRUE, 
                      scale = 2, 
                      alpha = 0.5, 
                      jittered_points = TRUE, 
                      point_alpha = 0.25, 
                      point_size = 0.5) +
  labs(y = 'Millennium BP', x = 'Mean annual temperature') +
  geom_vline(xintercept = as.numeric(bio1_limit), linetype = 2, color = 'red') +
  scale_fill_brewer(palette = 'Spectral', guide = 'none') +
    scale_x_continuous(limits = c(0, 32))

arch_dens_lgmr <- lgmr_extract_test %>%
  ggplot(aes(sat, mil)) +
  scale_y_discrete(limits = rev) +
  geom_density_ridges(aes(fill = mil), 
                      panel_scaling = TRUE, 
                      scale = 2, 
                      alpha = 0.5, 
                      jittered_points = TRUE, 
                      point_alpha = 0.25, 
                      point_size = 0.5) +
  labs(y = 'Millennium BP', x = 'Mean annual temperature') +
    geom_vline(xintercept = as.numeric(bio1_limit), linetype = 2, color = 'red') +
  scale_fill_brewer(palette = 'Spectral', guide = 'none') +
    scale_x_continuous(limits = c(0, 32))

# the difference between Chelsa-trace and LGMR ensemble mean at each point in time/space
arch_dens_diff <- lgmr_extract_test %>%
  ggplot(aes(sat - MAT, mil)) +
  scale_y_discrete(limits = rev) +
  geom_density_ridges(aes(fill = mil), 
                      panel_scaling = TRUE, 
                      scale = 2, 
                      alpha = 0.5, 
                      jittered_points = TRUE, 
                      point_alpha = 0.25, 
                      point_size = 0.5) +
  labs(y = 'Millennium BP', x = 'Difference (C)') +
   geom_vline(xintercept = 0, linetype = 2, color = 'red') +
  scale_fill_brewer(palette = 'Spectral', guide = 'none')

# why don't the tags work here?
(arch_dens_mat / arch_dens_lgmr + plot_layout(axes = 'collect')) | arch_dens_diff + plot_layout(widths = c(1, .1))  + plot_annotation(tag_levels = 'A', tag_suffix = ')') 
```

{{< pagebreak >}}

## Fig. S4.

```{r}
#| label: fig-country-summaries
#| fig-width: 8
#| fig-height: 6
#| fig-cap: "Projected increases in land area surpassing key temperature thresholds in each of the top 15 rice-producing countries in east Asia."
country_stats %>% 
  ggplot(aes(ssp, percent, group = variable, color = variable)) +
  facet_wrap(~name) +
  scale_color_manual(values = c('#abdda4', '#fdae61', '#d7191c'
)) +
  geom_line(linewidth = 1.2) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

{{< pagebreak >}}


## Fig. S5.

```{r}
#| label: fig-niche-all-models-bio1
#| cache: true
#| fig-width: 8
#| fig-height: 12
#| fig-cap: Predicted changes in mean annual temperature over currently cultivated rice areas in Asia for multiple CMIP6 ensemble members.

ggplot() +
  geom_stars(data = slice(cmip6, 'variable', 1) > units::drop_units(bio1_limit), downsample = 20) +
  facet_grid(model~ssp) +
  scale_fill_manual(values = c('grey', 'red'), 
                    name = paste0('MAT > ', bio1_limit), 
                    na.value = NA, na.translate = FALSE) +
  geom_sf(data = coasts) +
  labs(x = '', y = '')
```

{{< pagebreak >}}

## Fig. S6.

```{r}
#| label: fig-niche-all-models-bio10
#| cache: true
#| fig-width: 8
#| fig-height: 12
#| fig-cap: Predicted changes in mean maximum temperature of the warmest quarter over currently cultivated rice areas in Asia for multiple CMIP6 ensemble members.

ggplot() +
  geom_stars(data = slice(cmip6, 'variable', 2) > units::drop_units(bio10_limit), downsample = 20) +
  facet_grid(model~ssp) +
  scale_fill_manual(values = c('grey', 'red'), 
                       name = paste0('TWARM > ', bio10_limit),
                    na.value = NA, na.translate = FALSE) +
  geom_sf(data = coasts) +
  labs(x = '', y = '')
```

{{< pagebreak >}}

## Fig. S7.
```{r}
#| label: fig-niche-all-models-bio5
#| cache: true
#| fig-width: 8
#| fig-height: 12
#| fig-cap: Predicted changes in mean maximum temperature of the warmest month over currently cultivated rice areas in Asia for multiple CMIP6 ensemble members.

ggplot() +
  geom_stars(data = slice(cmip6, 'variable', 3) > units::drop_units(bio5_limit), downsample = 20) +
  facet_grid(model~ssp) +
  scale_fill_manual(values = c('grey', 'red'), 
                    name = paste0('TMAX > ', bio5_limit), 
                    na.value = NA, na.translate = FALSE) +
  geom_sf(data = coasts) +
  labs(x = '', y = '')
```

{{< pagebreak >}}

## Fig. S8.

```{r}
#| label: fig-displacement
#| fig-width: 6
#| fig-height: 3
#| fig-cap: "Estimated displacement of the optimal growing location of rice landraces away from the equator, based on genetic offset analysis across three future temperature scenarios. The x-axis indicates the difference between the absolute projected latitude in the future scenario and the absolute latitude today, with positive values indicating a shift in the optimal growing location of a given population away from the equator."

list(japonica = readRDS(here('data/data-derived/japonica_lat_shift.rds')),
     indica = readRDS(here('data/data-derived/indica_lat_shift.rds'))) |>
  bind_rows(.id = 'landrace') |>
  mutate(ssp = case_when(name == 'diff2.6' ~ 'SSP1-2.6',
                         name == 'diff7.0' ~ 'SSP3-7.0',
                         name == 'diff8.5' ~ 'SSP5-8.5')) |>
ggplot(aes(x = value, fill = ssp)) +
  geom_density(alpha = 0.3) +
  facet_grid(landrace ~ ssp) +
  geom_vline(xintercept = 0, linetype = 2) +
  scale_fill_brewer(palette = 'Spectral', direction = -1) +
  labs(x = 'Latitudinal displacement (degrees)')
```

{{< pagebreak >}}

## Table S1.

```{r}
#| label: tbl-quantiles
#| tbl-cap: "Present-day rice extent quantiles across three datasets of varying resolution and spatiotemporal support, compared to those calculated from archaeological sites in Asia throughout the Holocene."

quants_mod_monfreda <- monfreda_occ %>%
  st_drop_geometry() %>%
  select(bio1, bio5, bio10) %>%
  mutate(across(everything(), ~units::set_units(.x, 'degree_C'))) %>%
  reframe(across(everything(), 
                   ~quantile(.x, quantiles, type = 8))) %>%
  round(1) %>%
  mutate(quantile = quantiles, .before = 1)

quants_mod_gbif <- occ_dat %>%
  st_drop_geometry() %>%
  select(bio1, bio5, bio10) %>%
  mutate(across(everything(), ~units::set_units(.x, 'degree_C'))) %>%
  reframe(across(everything(), 
                   ~quantile(.x, quantiles, type = 8))) %>%
  round(1) %>%
  mutate(quantile = quantiles, .before = 1)

quants_arch <- arch_trace_dat %>%
  st_drop_geometry() %>%
  select(bio1 = MAT, bio5 = tmax, bio10 = twarm) %>%
  mutate(across(everything(), ~units::set_units(.x, 'degree_C'))) %>%
  reframe(across(everything(), 
                   ~quantile(.x, quantiles, type = 8))) %>%
  round(1) %>%
  mutate(quantile = quantiles, .before = 1)

left_join(quants_mod, quants_mod_monfreda, by = 'quantile') %>%
  left_join(quants_mod_gbif, by = 'quantile') %>%
  left_join(quants_arch, by = 'quantile') %>%
  units::drop_units() %>% # do we want celsius units?
  mutate(quantile = set_units(quantile * 100, '%')) %>% 
  select(quantile, bio1.x, bio1.y, bio1.x.x, bio1.y.y, bio5.x, bio5.y, bio5.x.x, bio5.y.y, bio10.x, bio10.y, bio10.x.x, bio10.y.y) %>%
  setNames(c('Quantile', rep(c('IRRI', 'Mon.', 'GBIF', 'Arch.'), 3))) %>%
  knitr::kable() |>
  kableExtra::add_header_above(tibble(names = c('', 'MAT', 
                                                'TMAX', 
                                                'TWARM'), 
                                      spans = c(1,4,4,4)))  
```

{{< pagebreak >}}

## Table S2.

```{r}
#| label: tbl-country-summaries-table
#| tbl-cap: "Projected increases in land area surpassing key temperature thresholds in each of the top 15 rice-producing countries in east Asia."
#| tbl-subcap:
#|   - "Percent land area surpassing MAT threshold"
#|   - "Percent land area surpassing TWARM threshold"
#|   - "Percent land area surpassing TMAX threshold"

# this is total land area??
# country_stats %>%
#   filter(variable == 'Mean annual temperature') %>%
#   select(-percent, -area) %>%
#   pivot_wider(names_from = ssp, 
#               values_from = sum) %>%
#   select(Country = name, Present = present, `SSP1-2.6`:`SSP5-8.5`) %>%
#   summarise(across(Present:`SSP5-8.5`, ~sum(.x))) %>%
#   mutate(across(everything(), ~.x / Present))

country_stats %>%
  mutate(percent = round(percent)) %>%
  filter(variable == 'Mean annual temperature') %>%
  select(-sum, -area) %>%
  pivot_wider(names_from = ssp, 
              values_from = percent) %>%
  select(Country = name, Present = present, `SSP1-2.6`:`SSP5-8.5`) %>%
  knitr::kable()


country_stats %>%
  mutate(percent = round(percent)) %>%
  filter(variable == 'Max temperature of warmest quarter') %>%
    select(-sum, -area) %>%
  pivot_wider(names_from = ssp,
              values_from = percent) %>%
  select(Country = name, Present = present, `SSP1-2.6`:`SSP5-8.5`) %>%
  knitr::kable()

country_stats %>%
  mutate(percent = round(percent)) %>%
  filter(variable == 'Max temperature of warmest month') %>%
    select(-sum, -area) %>%
  pivot_wider(names_from = ssp,
              values_from = percent) %>%
  select(Country = name, Present = present, `SSP1-2.6`:`SSP5-8.5`) %>%
  knitr::kable()
```

```{r}
knitr::knit_exit()
```


```{r}
#| label: fig-recon-eof
#| fig-width: 12
#| fig-height: 12
#| fig-cap: "Empirical orthogonal function analysis of Holocene temperature reconstruction reveals two leading modes of variability. We focus on the period from 7000 to 1000 years ago to remove impacts from the last deglaciation and contemporary greenhouse gas emissions. These two modes reflect trends in North and South Asian variability. The northern part of China has become cooler while the South has become warmer over time."
  

# library(tidyEOF)
# pat <- get_patterns(erb_decadal %>% filter(between(time, -10000, -2000)), 
#                     k = 2, scale = TRUE, rotate = TRUE)
# eof <- plot_eofs(pat) +
#   geom_sf(data = coasts)
# 
# amp <- plot_amps(pat, scaled = TRUE) + 
#   geom_smooth()
# 
# 
# sf_use_s2(FALSE)
# lgmr <- read_ncdf('~/Dropbox (UFL)/LGMR_SAT_climo.nc', eps = .001, proxy = FALSE) |>
#   select(sat) |>
#   st_crop(st_bbox(erb_decadal)) |>
#   units::drop_units() |>
#   st_set_dimensions(names = c('x', 'y', 'time')) |>
#   filter(between(time, 2000, 10000))
# sf_use_s2(TRUE)
# 
# lgmr_pat <- get_patterns(lgmr, k = 2, scale = TRUE, rotate = TRUE)
# lgmr_eof <- plot_eofs(lgmr_pat) +
#   geom_sf(data = coasts)
# 
# lgmr_amp <- plot_amps(lgmr_pat) + 
#   geom_smooth()
# 
# 
# (eof / amp + plot_layout(heights = c(2,1))) | (lgmr_eof / lgmr_amp + plot_layout(heights = c(2,1))) + plot_annotation(tag_levels = 'A', tag_suffix = ')')
```

```{r fig.asp = 1}
# sf_use_s2(FALSE)
# tmp <- here('../synchrony/data/data-raw/trace.01-36.22000BP.cam2.TREFHT.22000BP_decavg_400BCE.nc') |>
#   read_ncdf(var = 'TREFHT', eps = 0.01) |>
#   st_set_dimensions('lon', names = 'x') |>
#   st_set_dimensions('lat', names = 'y') |>
#   st_warp(st_as_stars(st_bbox(), dx = 3.75, dy = 3.709)) |>
#   filter(between(time, -10, -2)) |>
#   st_crop(st_bbox(erb_decadal))
# sf_use_s2(TRUE)
# 
# st_apply(tmp, 3, mean) |>
#   as_tibble() |>
#   ggplot(aes(time, mean)) +
#   geom_line()
# 
# trace_pat_low <- get_patterns(tmp, k = 2, scale = TRUE, rotate = TRUE)
# 
# trace_eof_low <- plot_eofs(trace_pat_low) +
#   geom_sf(data = coasts)
# 
# trace_amp_low <- plot_amps(trace_pat_low) +
#   geom_smooth()
# 
# trace_eof_low / trace_amp_low + plot_layout(heights = c(2,1))
```

```{r}
# trace_bio1_pat <- get_patterns(chelsa_trace['bio1'] |> filter(between(time, 2, 10)), k = 2, scale = FALSE, rotate = TRUE)
# trace_bio1_eof <- plot_eofs(trace_bio1_pat) +
#   geom_sf(data = coasts)
# trace_bio1_amp <- plot_amps(trace_bio1_pat) +
#   geom_smooth() +
#   scale_x_reverse(breaks = seq(0, 12, 2))
# 
# trace_bio5_pat <- get_patterns(chelsa_trace['bio5'], k = 3, scale = TRUE)
# trace_bio5_eof <- plot_eofs(trace_bio5_pat) +
#   geom_sf(data = coasts)
# trace_bio5_amp <- plot_amps(trace_bio5_pat) +
#   geom_smooth() +
#   scale_x_reverse(breaks = seq(0, 12, 2))
# 
# trace_bio10_pat <- get_patterns(chelsa_trace['bio10'], k = 3, scale = TRUE)
# trace_bio10_eof <- plot_eofs(trace_bio10_pat) +
#   geom_sf(data = coasts)
# trace_bio10_amp <- plot_amps(trace_bio10_pat) +
#   geom_smooth() +
#   scale_x_reverse(breaks = seq(0, 12, 2))
# 
# 
# trace_bio1_eof / trace_bio1_amp + plot_layout(heights = c(2,1))
# trace_bio5_eof / trace_bio5_amp + plot_layout(heights = c(2,1))
# trace_bio10_eof / trace_bio10_amp + plot_layout(heights = c(2,1))
```

```{r}
#new_erb_times <- erb_decadal |>
#  st_get_dimension_values('time') %>% 
#  `*`(-1) |>
#  years() %>%
#  `-`(ym('1950-01'), .)

# new_lgmr_times <- lgmr_rast |>
#   st_get_dimension_values('time') |>
#   years() %>%
#   `-`(ym('1950-01'), .)
# 
# #erb_decadal2 <- erb_decadal[,,,1200:1] |> st_set_dimensions('time', values = rev(new_erb_times))
# # library(terra)
# lgmr2 <- lgmr_rast |>
#   st_set_dimensions('time', values = (new_lgmr_times)) %>%
#   .[,,,61:1]
#   #terra::rast() |>
#   #terra::disagg(method = 'bilinear', fact = 10) %>%
#   #.[[61:1]] |>
#   #st_as_stars() |>
#   #st_set_dimensions('time', values = rev(new_lgmr_times))
# 
# arch_trace_2 <- arch_trace_dat |>
#   mutate(time = ym('1950-01') - years(as.integer(med_age) * -1))
# 
# #erb_extract_test <- arch_trace_2 %>%
# #  st_extract(erb_decadal2, ., time_column = 'time', interpolate_time = TRUE) %>%
# #  st_drop_geometry() %>%
# #  bind_cols(arch_trace_dat, .) |>
# #  remove_missing()
# 
# 
# lgmr_extract_test <- arch_trace_2 %>%
#   st_extract(lgmr2, ., time_column = 'time', interpolate_time = TRUE) %>%
#   st_drop_geometry() %>%
#   bind_cols(arch_trace_dat, .) |>
#   remove_missing()

# tmp_times <- tmp |># low res trace
#     st_get_dimension_values('time') %>%
#   `*`(-1000) |>
#   as.integer() |>
#     years() %>%
#     `-`(ym('1950-01'), .)
# 
# tmp2 <- tmp |> 
#   st_set_dimensions('time', values = tmp_times)
# 
# tmp_extract_test <- arch_trace_2 %>%
#   st_extract(tmp2, ., time_column = 'time', interpolate_time = TRUE) %>%
#   st_drop_geometry() %>%
#   bind_cols(arch_trace_dat, .) |>
#   remove_missing()
# 
# 
#   
# time(tmp2)
# tmp3 <- tmp2 |>
#   aggregate(by = tmp_times[seq(1, 1210, 10)], FUN = mean) |> # average to centuries
#   aperm(c(3, 1, 2))
# 
# tmp3
# lgmr2
# tmp_extract_test2 <- arch_trace_2 %>%
#   st_extract(tmp3, ., time_column = 'time', interpolate_time = TRUE) %>%
#   st_drop_geometry() %>%
#   bind_cols(arch_trace_dat, .) |>
#   remove_missing()
```

```{r}

# arch_dens_mat <- erb_extract_test %>%
#   ggplot(aes(MAT, mil)) +
#   scale_y_discrete(limits = rev) +
#   geom_density_ridges(aes(fill = mil), 
#                       panel_scaling = TRUE, 
#                       scale = 2, 
#                       alpha = 0.5, 
#                       jittered_points = TRUE, 
#                       point_alpha = 0.25, 
#                       point_size = 0.5) +
#   labs(y = 'Millennium BP', x = 'Mean annual temperature') +
#   geom_vline(xintercept = as.numeric(bio1_limit), linetype = 2, color = 'red') +
#   scale_fill_brewer(palette = 'Spectral', guide = 'none') +
#     scale_x_continuous(limits = c(0, 32))

```



```{r}
# sanity check against present data
# trace_tmp <- read_stars('../asia-holocene/data/data-derived/trace_tmp.tif')[,,,121, drop = TRUE]
# 
# base_test <- arch_trace_2 %>%
#   st_extract(trace_tmp, .) %>%
#   st_drop_geometry() %>%
#   bind_cols(arch_trace_dat, .) |>
#   remove_missing()
# 
# lgmr_test <- arch_trace_2 %>% # this is just the present time period?
#   st_extract(lgmr[,,,1, drop = TRUE], .) %>%
#   st_drop_geometry() %>%
#   bind_cols(lgmr_extract_test, .) |>
#   remove_missing()
# 
# 
# arch_dens_erb <- erb_extract_test %>%
#   ggplot(aes(tas, mil)) +
#   scale_y_discrete(limits = rev) +
#   geom_density_ridges(aes(fill = mil), 
#                       panel_scaling = TRUE, 
#                       scale = 2, 
#                       alpha = 0.5, 
#                       jittered_points = TRUE, 
#                       point_alpha = 0.25, 
#                       point_size = 0.5) +
#   labs(y = 'Millennium BP', x = 'Mean annual temperature') +
#   scale_fill_brewer(palette = 'Spectral', guide = 'none')
# 
# 
# 
# 
# arch_dens_base <- base_test %>%
#   ggplot(aes(`trace_tmp.tif`, mil)) +
#   scale_y_discrete(limits = rev) +
#   geom_density_ridges(aes(fill = mil), 
#                       panel_scaling = TRUE, 
#                       scale = 2, 
#                       alpha = 0.5, 
#                       jittered_points = TRUE, 
#                       point_alpha = 0.25, 
#                       point_size = 0.5) +
#   labs(y = 'Millennium BP', x = 'Mean annual temperature') +
#     geom_vline(xintercept = as.numeric(bio1_limit), linetype = 2, color = 'red') +
#   scale_fill_brewer(palette = 'Spectral', guide = 'none') +
#   scale_x_continuous(limits = c(0, 32))
# 
# arch_dens_base_2 <- base_test %>%
#   ggplot(aes(MAT - `trace_tmp.tif`, mil)) +
#   scale_y_discrete(limits = rev) +
#   geom_density_ridges(aes(fill = mil), 
#                       panel_scaling = TRUE, 
#                       scale = 2, 
#                       alpha = 0.5, 
#                       jittered_points = TRUE, 
#                       point_alpha = 0.25, 
#                       point_size = 0.5) +
#   labs(y = 'Millennium BP', x = 'Mean annual temperature') +
#   scale_fill_brewer(palette = 'Spectral', guide = 'none')
# 
# arch_dens_base_lgmr <- lgmr_test %>%
#   ggplot(aes(sat...12 - sat...14, mil)) +
#   scale_y_discrete(limits = rev) +
#   geom_density_ridges(aes(fill = mil), 
#                       panel_scaling = TRUE, 
#                       scale = 2, 
#                       alpha = 0.5, 
#                       jittered_points = TRUE, 
#                       point_alpha = 0.25, 
#                       point_size = 0.5) +
#   labs(y = 'Millennium BP', x = 'Mean annual temperature') +
#   scale_fill_brewer(palette = 'Spectral', guide = 'none')
# 
# arch_dens_trace <- tmp_extract_test %>%
#   ggplot(aes(TREFHT - 273.15, mil)) +
#   scale_y_discrete(limits = rev) +
#   geom_density_ridges(aes(fill = mil), 
#                       panel_scaling = TRUE, 
#                       scale = 2, 
#                       alpha = 0.5, 
#                       jittered_points = TRUE, 
#                       point_alpha = 0.25, 
#                       point_size = 0.5) +
#   labs(y = 'Millennium BP', x = 'Mean annual temperature') +
#   scale_fill_brewer(palette = 'Spectral', guide = 'none') +
#       geom_vline(xintercept = as.numeric(bio1_limit), linetype = 2, color = 'red') 
# 
# 
# arch_dens_trace2 <- tmp_extract_test2 %>% # century averages
#   ggplot(aes(TREFHT - 273.15, mil)) +
#   scale_y_discrete(limits = rev) +
#   geom_density_ridges(aes(fill = mil), 
#                       panel_scaling = TRUE, 
#                       scale = 2, 
#                       alpha = 0.5, 
#                       jittered_points = TRUE, 
#                       point_alpha = 0.25, 
#                       point_size = 0.5) +
#   labs(y = 'Millennium BP', x = 'Mean annual temperature') +
#   scale_fill_brewer(palette = 'Spectral', guide = 'none') +
#       geom_vline(xintercept = as.numeric(bio1_limit), linetype = 2, color = 'red') 
# 
# #arch_dens_mat +  arch_dens_lgmr + arch_dens_trace + arch_dens_trace2 + plot_layout(axes = 'collect')  + plot_annotation(tag_levels = 'A') 
# #+ arch_dens_base 

```

```{r}
#arch_dens_mat + arch_dens_base 

#arch_dens_base_2 + arch_dens_erb + arch_dens_base_lgmr + plot_layout(axes = 'collect')

```
