---
title: "Crop GDD"
author: "Nick Gauthier"
date: "`r Sys.Date()`"
output: html_document
---

Crop thresholds from GAEZ appendicies -- abandoned for now because these aren't as straightforward as they seem.

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(here)
```

```{r}
dat <- read_excel(here('data', 'GAEZ4_appendices.xlsx'), sheet = 2, skip = 2) %>%
   select(id = `Crop/LUT`,
          name = `Crop/LUT name`, 
          tbase = `Minimum temperature`, 
          low_bnd = `Lower boundary of accumulated heat units range (dd)`,
          low_opt = `Lower boundary of optimum accumulated heat units (dd)`,
          upper_opt = `Upper boundary of optimum accumulated heat units (dd)`,
          upper_bnd = `Upper boundary of accumulated heat units range (dd)`) %>%
    filter(name %in% c('Winter wheat', 
                       'Buckwheat', 
                       'Foxtail millet', 
                       'Japonica wetland rice', 
                       'Indica wetland rice', 
                       'Indica dryland rice'))
```


```{r}
dat %>%
  group_by(name) %>%
  summarise(tbase = mean(tbase)) %>% 
  ggplot(aes(reorder(name, tbase), tbase)) + 
  geom_col()
```

```{r}
dat %>%
    pivot_longer(low_bnd:upper_bnd, names_to = 'type', values_to = 'gdd') %>%
  mutate(type = factor(type, levels = c('low_bnd', 'low_opt', 'upper_opt', 'upper_bnd'))) %>%
  group_by(name, type) %>%
  summarise(mean = mean(gdd), min = min(gdd), max = max(gdd)) %>%
  ggplot(aes(type)) +
  geom_linerange(aes(ymin = min, ymax = max)) +
  geom_point(aes(y = mean)) +
  facet_wrap(~name)
```

```{r}
dat %>%
  pivot_longer(low_bnd:upper_bnd, names_to = 'type', values_to = 'gdd') %>%
    mutate(suitability = if_else(type %in% c('low_bnd', 'upper_bnd'), 0, 1) ) %>%
  ggplot(aes(gdd, group = id, color = id)) +
  geom_line(aes(y = suitability)) +
  facet_wrap(~name) +
  theme_bw()
```


