---
title: "GBIF"
author: "Nick Gauthier"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(stars)
library(tidyverse)
```

GBIF.org (07 October 2022) GBIF Occurrence Download  https://doi.org/10.15468/dl.j3km5h


```{r}
era <- readRDS('data/data-derived/era_gdd.rds')
```

```{r}
plot(era)
```
```{r}
progenitor <- read_csv('data/wild_progenitor.csv') %>%
    st_as_sf(coords = c('X_WGS84', 'Y_WGS84'), crs = 4326)

plot(progenitor)
```

```{r}
gbif <- read_tsv('~/Downloads/0058828-220831081235567.csv') %>%
  st_as_sf(coords = c('decimalLongitude', 'decimalLatitude'), crs = 4326)
```

```{r}
gbif
```

```{r}
plot(st_geometry(gbif))
```

```{r}
plot(st_crop(gbif, st_bbox(era)))
```

```{r}
plot(st_crop(progenitor, st_bbox(era)))

```


```{r}
plot(st_apply(era, 1:2, mean))
```

```{r}
tibet <- read_sf('data/data-raw/shapefiles/DBATP/DBATP_Polygon.shp')

ggplot() +
  geom_stars(data = st_apply(units::drop_units(era['gdd5']) > 2500, 1:2, sum) / 72 * 100, na.action = na.omit) +
    scale_fill_viridis_c(option = 'magma') +
  geom_sf(data = tibet, fill = NA) +
  theme_bw()
```

```{r}
ggplot() +
  geom_stars(data = st_apply(era[,,,50:72], 1:2, mean) - st_apply(era[,,,1:20], 1:2, mean)) +
  scale_fill_distiller(palette = 'RdBu', limits = c(-555, 555))
```


```{r}
ggplot() +
  geom_stars(data = st_apply(era[,,,42:72], 1:2, mean) - st_apply(era[,,,1:30], 1:2, mean), na.action = na.omit) +
  scale_fill_distiller(palette = 'RdBu', limits = c(-440, 440)) +
  theme_bw()
```

```{r}
pro <- st_extract(st_apply(era[,,,1:51], 1:2, mean), progenitor)

ggplot(pro, aes(gdd5)) +
  geom_density()
```


```{r}
gdd <- st_extract(st_apply(era[,,,1:51], 1:2, mean), gbif)
```

```{r}
ggplot(gdd, aes(gdd0)) +
  geom_density()
```




```{r}
bind_cols(gbif, gdd) %>%
  filter(gdd0 < 2000)
```

```{r}
bind_cols(gbif, gdd) %>%
  filter(year < 1970) %>%
ggplot(aes(gdd10)) +
  geom_density()
```

```{r}
rice <- read_sf('~/Downloads/Rice Archaeological Database.kml') %>%
  st_zm()
  st_transform(st_crs(era))
```

```{r}
plot(rice)
```

```{r}
era_mean <- st_apply(era[,,,1:51], 1:2, mean)
st_extract(era_mean, st_geometry(rice)) %>%
  st_drop_geometry() %>%
  remove_missing() %>%
  pivot_longer(everything()) %>%
  ggplot(aes(value)) +
  facet_wrap(~name) + 
  geom_density()
```

```{r}
rice$Description %>% map(str_split, '<br>')
```



```{r}

rice_map <- read_stars('~/Downloads/rice_HarvAreaYield_Geotiff/rice_YieldPerHectare.tif') %>%
  st_warp(era_mean)

plot(rice_map)
```

```{r}
c(rice_map, era_mean) %>%
  as_tibble() %>%
  ggplot(aes(gdd10, rice_YieldPerHectare.tif)) +
  geom_point(alpha = 0.1) +
  geom_smooth()
```

```{r}
spamCrops()
rice_map2 <- crop_spam('rice', var = 'area') %>%
  st_as_stars() %>%
  st_warp(era_mean)
```

```{r}
plot(rice_map2[,,,1])
```
```{r}
c(slice(rice_map2, 'attributes', 1), era_mean) %>%
  as_tibble() %>%
  ggplot(aes(gdd5, spam2010V1r1_global_H_RICE_A.tif)) + # areas
  geom_point(alpha = 0.1) +
  geom_smooth()
```

```{r}
c(slice(rice_map2, 'attributes', 1), era_mean) %>%
  as_tibble() %>%
  filter(spam2010V1r1_global_H_RICE_A.tif > 0) %>%
  ggplot(aes(gdd0)) + # areas
  geom_density()
```

