---
title: "Untitled"
author: "Nick Gauthier"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stars)
library(tidyverse)
asia_bbox_sf <- st_bbox(c(xmin = 60, xmax = 150, ymin = -20, ymax = 50), crs = 4326)

bio10 <- read_ncdf('~/Dropbox (UFL)/dataset-sis-biodiversity-cmip5-global-44dac759-9b50-4f84-ae9e-97c80c01c0b8/BIO10_gfdl-esm2m_rcp45_r1i1p1_1950-2100_v1.0.nc') %>% st_crop(asia_bbox_sf) %>%
 mutate(BIO10 = units::set_units(BIO10, degree_C))
bio1 <- read_ncdf('~/Dropbox (UFL)/dataset-sis-biodiversity-cmip5-global-44dac759-9b50-4f84-ae9e-97c80c01c0b8/BIO01_gfdl-esm2m_rcp45_r1i1p1_1950-2100_v1.0.nc') %>% st_crop(asia_bbox_sf) %>%
 mutate(BIO01 = units::set_units(BIO01, degree_C))

bio5 <- read_ncdf('~/Dropbox (UFL)/dataset-sis-biodiversity-cmip5-global-44dac759-9b50-4f84-ae9e-97c80c01c0b8/BIO05_gfdl-esm2m_rcp45_r1i1p1_1950-2100_v1.0.nc') %>% st_crop(asia_bbox_sf) %>%
 mutate(BIO05 = units::set_units(BIO05, degree_C))
```

```{r}
thresh10 <- (bio10 > 32.7) 
thres01 <- bio1 > 28.2
thres05 <- bio5 > 40.4

```


```{r}


ggplot() +
  geom_stars(data = thresh10 %>% st_apply(1:2, sum) ) +
  coord_quickmap()
ggplot() +
  geom_stars(data = thres01 %>% st_apply(1:2, sum) ) +
  coord_quickmap()
ggplot() +
  geom_stars(data = thres05 %>% st_apply(1:2, sum) ) +
  coord_quickmap()
```

```{r}
thresh10 %>% st_apply(3, sum) %>% as_tibble()  %>% ggplot(aes(time, sum)) + geom_line()
thres01 %>% st_apply(3, sum) %>% as_tibble()  %>% ggplot(aes(time, sum)) + geom_line()
thres05 %>% st_apply(3, sum) %>% as_tibble()  %>% ggplot(aes(time, sum)) + geom_line()

```
```{r}
c(bio1, bio5) %>%
  st_apply(1:2, function(x) cor(x$BIO01, x$BIO05)) %>% plot
cor(bio1['BIO01'], bio5['BIO05'])

cor1 <- raster::corLocal(as(bio1, 'Raster'), as(bio5, 'Raster')) %>% st_as_stars()
cor2 <- raster::corLocal(as(bio1, 'Raster'), as(bio10, 'Raster')) %>% st_as_stars()
cor3 <- raster::corLocal(as(bio10, 'Raster'), as(bio5, 'Raster')) %>% st_as_stars()


ggplot() +
  geom_stars(data = c(cor1, cor2, cor3, along = 'time')) +
  facet_wrap(~time) +
  coord_quickmap() +
  scale_fill_viridis_c(limits = c(0, 1))
```

```{r}
c(thres01, thres05) %>%
  mutate(test = (BIO01 == BIO05) & (BIO01 == TRUE)) %>%
select(test) %>%
  st_apply(1:2, sum)

ggplot() +
  geom_stars(data = c(thres01, thres05) %>%
  mutate(test = (BIO01 == BIO05) & (BIO01 == TRUE)) %>%
select(test) %>%
  st_apply(1:2, sum))+ coord_quickmap()

ggplot() +
  geom_stars(data = c(thresh10, thres05) %>%
  mutate(test = (BIO10 == BIO05) & (BIO10 == TRUE)) %>%
select(test) %>%
  st_apply(1:2, sum))+ coord_quickmap()

ggplot() +
  geom_stars(data = c(thresh10, thres01) %>%
  mutate(test = (BIO10 == BIO01) & (BIO10 == TRUE)) %>%
select(test) %>%
  st_apply(1:2, sum))+ coord_quickmap()
```

```{r}
library(tidyEOF)

plot_scree(bio1 %>% st_set_dimensions(names = c('x', 'y', 'time')), scale = FALSE)


get_patterns(bio1 %>% st_set_dimensions(names = c('x', 'y', 'time')), scale = TRUE, k = 4 , rotate = FALSE) %>% plot_eofs()
get_patterns(bio1 %>% st_set_dimensions(names = c('x', 'y', 'time')), scale = TRUE, k = 4 , rotate = FALSE) %>% plot_amps()


get_patterns(bio5 %>% st_set_dimensions(names = c('x', 'y', 'time')), scale = TRUE, k = 4 , rotate = FALSE) %>% plot_eofs()
get_patterns(bio5 %>% st_set_dimensions(names = c('x', 'y', 'time')), scale = TRUE, k = 4 , rotate = FALSE) %>% plot_amps()


get_patterns(bio10 %>% st_set_dimensions(names = c('x', 'y', 'time')), scale = TRUE, k = 4 , rotate = FALSE) %>% plot_eofs()
get_patterns(bio10 %>% st_set_dimensions(names = c('x', 'y', 'time')), scale = TRUE, k = 4 , rotate = FALSE) %>% plot_amps()
```

```{r}
library(logisticPCA)
test <- thresh10$BIO10
dim(test) <- c(25200, 151)
logpca_cv = cv.lpca(t(test), ks = 2, ms = 1:10)
plot(logpca_cv)
logpca_model = logisticPCA(, k = 2, m = which.min(logpca_cv))
```

