---
title: "japan map"
author: "Nick Gauthier"
date: "9/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stars)
library(tidyverse)
countries <- rnaturalearth::ne_countries(country = c('Japan', 
                                                     'South Korea', 
                                                     'North Korea'), 
                                         returnclass = 'sf', 
                                         scale = 'medium')
plot(countries)
```

```{r}
gdd <- read_stars('~/Downloads/CHELSA_gdd10_1981-2010_V.2.1.tif') %>%
  st_crop(countries) %>%
  setNames('GDD10')
```

```{r}
ggplot() +
  geom_stars(data = gdd) +
  scale_fill_viridis_c(option = 'magma', na.value = NA) +
  geom_sf(data = countries, fill = NA) +
  coord_sf(ylim = c(30, 45)) +
  theme_bw()
```

```{r}
gdd_class <- gdd %>% 
  transmute(niche = case_when(GDD10 > 3300 ~ 'Tropical Japonica (130 day)',
                              GDD10 > 3000 ~ 'Temperate Japonica (150 day) and Indica (120 day)',
                              GDD10 > 2900 ~ 'Tropical Japonica (120 day)',
                              GDD10 > 2500 ~ 'Temperate Japonica (130 day)',
                              GDD10 > 2400 ~ 'Indica (110 day)',
                              !is.na(GDD10) ~ 'None') %>%
              factor(levels = c('None', 'Indica (110 day)', 
                                'Temperate Japonica (130 day)', 
                                'Tropical Japonica (120 day)', 
                                'Indica (120 day) or Temperate Japonica (150 day)', 
                                'Tropical Japonica (130 day)'))) 
```

```{r}
ggplot() +
  geom_stars(data = gdd_class) +
  scale_fill_brewer(palette = 'Spectral', direction = -1, na.value = NA) +
  geom_sf(data = countries, fill = NA) +
  coord_sf(ylim = c(30, 45)) +
  theme_bw()
```

## Polish Army Polygons

```{r}
rice_polys <- read_sf('japan_poly.shp') %>% 
  select(-id) %>% 
  replace_na(replace = list(type = 'rice')) %>%
  st_make_valid() %>%
  mutate(type = as.factor(type))

korea_polys <- read_sf('korea_poly.shp') %>% 
  select(-id) %>% 
  st_make_valid()
```

```{r}
plot(rice_polys)
plot(korea_polys)
```
```{r}
poly_mean <- aggregate(gdd, rice_polys, mean, na.rm = TRUE, exact = TRUE)
poly_sd <- aggregate(gdd, rice_polys, mean, na.rm = TRUE, exact = TRUE)
korea_mean <- aggregate(gdd, korea_polys, mean, na.rm = TRUE, exact = TRUE)
korea_sd <- aggregate(gdd, korea_polys, mean, na.rm = TRUE, exact = TRUE)
```

```{r}
test %>% plot
```
```{r}
st_crop(gdd, rice_polys) %>% plot
```
```{r}
test <- st_rasterize(rice_polys, dx = 0.00833333) %>% st_warp(gdd)

plot(test, downsample = 1)



test2 <- gdd %>% 
  st_crop(test) %>% 
  st_as_stars()

test3 <- gdd %>%
  st_as_stars() %>%
  c(test) %>%
  as_tibble() %>%
  filter(!is.na(GDD10)) %>%
  mutate(type = if_else(is.na(type), 'no rice', as.character(type)))

test3 %>%
  ggplot(aes(GDD10, group = type, fill = type)) +
  geom_density(alpha = .5) +
  theme_bw() +
  ggtitle('GDD10 distributions in Japan by land-use type')
```

```{r}
test3 %>%
  mutate(type = if_else(type == 'no rice', type, 'rice')) %>%
  ggplot(aes(GDD10, group = type, fill = type)) +
  geom_density(alpha = .5) +
  theme_bw() +
  ggtitle('GDD10 distributions in Japan by land-use type (simplified types)')
```
```{r}
test_k <- st_rasterize(korea_polys, dx = 0.00833333) %>% st_warp(gdd)

plot(test_k, downsample = 1)



test2k <- gdd %>% 
  st_crop(test_k) %>% 
  st_as_stars()

test3k <- gdd %>%
  st_as_stars() %>%
  c(test_k) %>%
  as_tibble() %>%
  filter(!is.na(GDD10)) %>%
  mutate(type = if_else(is.na(ID), 'no paddies', 'paddies'))


test3k %>%
  ggplot(aes(GDD10, group = type, fill = type)) +
  geom_density(alpha = .5) +
  theme_bw() +
  ggtitle('GDD10 distributions in Korea by land-use type')
```
^ look at quantiles/standard errors to find an objective threshold

```{r}
ggplot() +
  geom_stars(data = gdd > 2000) +
  scale_fill_viridis_d(option = 'magma', na.value = NA) +
  geom_sf(data = countries, fill = NA) +
  coord_sf(ylim = c(30, 45)) +
  theme_bw()
```

```{r}
threshold_poly <- st_as_sf(gdd > 1750, merge = TRUE, use_integer = TRUE, na.rm = TRUE)
```

```{r}
write_sf(threshold_poly, 'threshold.shp')
```


```{r}
as_tibble(test2) %>%
  left_join(as_tibble(test)) %>%
  remove_missing()

as_tibble(test) %>% remove_missing
as_tibble(test2) %>% remove_missing
```

